image: maven:latest

stages:
    - build
    - test
    - package

build:
    stage: build
    tags:
        - ugrad
    script: 
        - mvn compile

test:
    stage: test
    tags:
        - ugrad
    script: 
        - mvn test

package:
    stage: package
    tags:
        - ugrad
    script: 
        mvn package
