image: maven:latest

stages:
    - build
    - test
    - deploy

build:
    stage: build
    tags:
        - ugrad
    script: 
        - mvn clean package -DskipTests
        - echo "Build completed"
    artifacts:
        paths:
            - target/*.jar
        expire_in: 1 week

test:
    stage: test
    tags:
        - ugrad
    script: 
        - mvn clean verify
        - echo "Test completed"

deploy:
    stage: deploy
    tags:
        - ugrad
    script: 
        - echo "Not deployed yet"
