image: maven:latest

stages:
    - build
    - test
    - package

build:
    stage: build
    tags:
        - dalfcs_docker_autoscale
    script: 
        - mvn clean package -DskipTests
        - echo "Build completed"

test:
    stage: test
    tags:
        - ugrad
    script: 
        - mvn clean verify
        - echo "Test completed"

package:
    stage: package
    tags:
        - ugrad
    script: 
        - mvn package
